# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: todoapp_user
      POSTGRES_PASSWORD: TestPassw0rd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
